version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: amine
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: project_management
    ports:
      - "5455:5432"
    restart: always